[versions]
kotest = "5.9.1"
kotlin = "2.1.20"
kotlinx-coroutines = "1.10.1"
spring = "4.0.0"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-assertions-konform = "io.kotest.extensions:kotest-assertions-konform-jvm:1.3.0"
kotest-property = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-jpa-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.jpa:org.jetbrains.kotlin.plugin.jpa.gradle.plugin", version.ref = "kotlin" }
kotlin-logging = "io.github.oshai:kotlin-logging-jvm:7.0.5"
kotlin-spring-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinx-coroutines" }
ktlint-gradle = "org.jlleitschuh.gradle:ktlint-gradle:12.1.1"
mockk = "io.mockk:mockk-jvm:1.13.17"
postgresql = "org.postgresql:postgresql:42.7.8"
spring-boot-gradle-plugin = { module = "org.springframework.boot:org.springframework.boot.gradle.plugin", version.ref = "spring" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring" }
spring-dependency-management-gradle-plugin = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.1.7"

[bundles]
testing = [
    "kotest-assertions-core",
    "kotest-assertions-konform",
    "kotest-property",
    "kotest-runner-junit5",
    "mockk",
]

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
